### ISSUE TITLE
Unable to add module to application

### ISSUE THREAD

**Issue by oddlyfunctional** [gmostert/ng2-breadcrumb#26]
Hi! I tried to add this package to my application following the README:

```
import {Ng2BreadcrumbModule, BreadcrumbService} from 'ng2-breadcrumb/ng2-breadcrumb';

@NgModule({
    imports: [Ng2BreadcrumbModule],
    providers: [BreadcrumbService]
})
export class AppModule {
    ...
}
```

However, when I open the page, I receive this error:

<details>
<summary>`Uncaught Error: Unexpected value 'Ng2BreadcrumbModule' imported by the module 'AppModule'`</summary>
```
    at http://localhost/build/app.js:22183:35
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost/build/app.js:22168:44)
    at RuntimeCompiler._compileComponents (http://localhost/build/app.js:35048:47)
    at RuntimeCompiler._compileModuleAndComponents (http://localhost/build/app.js:34986:37)
    at RuntimeCompiler.compileModuleAsync (http://localhost/build/app.js:34977:21)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost/build/app.js:24632:25)
    at PlatformRef_.bootstrapModule (http://localhost/build/app.js:24614:21)
    at Object.<anonymous> (http://localhost/build/app.js:116900:53)
    at __webpack_require__ (http://localhost/build/app.js:654:30)(anonymous function) @ metadata_resolver.js:227CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:212RuntimeCompiler._compileComponents @ runtime_compiler.js:126RuntimeCompiler._compileModuleAndComponents @ runtime_compiler.js:64RuntimeCompiler.compileModuleAsync @ runtime_compiler.js:55PlatformRef_._bootstrapModuleWithZone @ application_ref.js:302PlatformRef_.bootstrapModule @ application_ref.js:284(anonymous function) @ main.ts:3__webpack_require__ @ bootstrap 66b5bbd…:653(anonymous function) @ bootstrap 66b5bbd…:700(anonymous function) @ bootstrap 66b5bbd…:700
```
</details>

Am I doing anything wrong?

**Comment by bchagas** [comment]
👍

**Comment by ZeeAzmat-punch** [comment]
+1

**Comment by jesperneelen** [comment]
+1

**Comment by bbrink68** [comment]
+1

**Comment by bbrink68** [comment]
I dug into this a bit, I am seeing typescript errors in the `BreadcrumbService`.  On line 10 & 11 the variables are typed as `Array<string>`, elsewhere in that service on lines 90, 99 & 108

```
// Typescript complains about this.
// "property includes does not exist on type string[]"
if (!this.hideRoutes.includes(route)) {
  this.hideRoutes.push(route);
}
```

Simply changing lines 10 & 11 to:

```
private hideRoutes: any = new Array<string>();
private hideRoutesRegex: [] = new Array<string>();
```

allowed this to start working for me.  Probably needs a better fix long term however.

**Comment by thiagogjt** [comment]
+1

**Comment by johnhamm** [comment]
+1

**Comment by johnhamm** [comment]
Changing lines 10 & 11 did not fix the problem for me.  Is this project abandoned?
