### ISSUE TITLE
could not install ng2-breadcrumbs on my Windows machine

### ISSUE THREAD

**Issue by lipinets** [gmostert/ng2-breadcrumb#64]
Hello,
node v7.10.0
npm  v4.2.0
I created folder, then
git clone 
npm install
npm start
Log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ng2-breadcrumb@0.5.14~prestart: ng2-breadcrumb@0.5.14
6 silly lifecycle ng2-breadcrumb@0.5.14~prestart: no script for prestart, continuing
7 info lifecycle ng2-breadcrumb@0.5.14~start: ng2-breadcrumb@0.5.14
8 verbose lifecycle ng2-breadcrumb@0.5.14~start: unsafe-perm in lifecycle true
9 verbose lifecycle ng2-breadcrumb@0.5.14~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\bc\ng2-breadcrumb\node_modules\.bin;C:\Users\ksn\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\ksn\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\Users\ksn\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_101\bin;C:\Ruby23-x64\bin;C:\Program Files (x86)\Skype\Phone;C:\Program Files\nodejs;C:\Program Files\Docker Toolbox;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\ksn\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle ng2-breadcrumb@0.5.14~start: CWD: D:\bc\ng2-breadcrumb
11 silly lifecycle ng2-breadcrumb@0.5.14~start: Args: [ '/d /s /c',
11 silly lifecycle   'tsc && concurrently "npm run ngc" "npm run lite" ' ]
12 silly lifecycle ng2-breadcrumb@0.5.14~start: Returned: code: 2  signal: null
13 info lifecycle ng2-breadcrumb@0.5.14~start: Failed to exec start script
14 verbose stack Error: ng2-breadcrumb@0.5.14 start: `tsc && concurrently "npm run ngc" "npm run lite" `
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ng2-breadcrumb@0.5.14
16 verbose cwd D:\bc\ng2-breadcrumb
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error ng2-breadcrumb@0.5.14 start: `tsc && concurrently "npm run ngc" "npm run lite" `
23 error Exit status 2
24 error Failed at the ng2-breadcrumb@0.5.14 start script 'tsc && concurrently "npm run ngc" "npm run lite" '.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the ng2-breadcrumb package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     tsc && concurrently "npm run ngc" "npm run lite"
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs ng2-breadcrumb
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls ng2-breadcrumb
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]

Could you help me to make it work? Thanks

**Comment by evanjmg** [comment]
I'd make sure you have node version of 6 or higher and npm of 3 or higher as well as look at my latest pull as I had trouble getting it working locally - https://github.com/gmostert/ng2-breadcrumb/pull/67
